var icons = {
  // "iOS": "📱",
  "Web Development": "<i class='fas fa-globe-americas'></i>",
  "AI Prompt Engineer": "🪄",
  "AI API Developer": "🪄",
  "AI Engineer": "🪄",
  "AWS Cloud": "<i class='fab fa-aws'></i>",
  // "AWS Cloud": "☁️",
  "Cross-Platform - React Native": "<i class='fab fa-react'></i>",
  "CompSci - DS, Algos, Systems, Logic": "💻",
  "Databases - MySQL, NoSQL, Firebase Firestore, and More!": "🗄️",
  "Data Structures, Algorithms, Architechtures, Systems Design": "Ω",
  "Enterprise - DevOps, Server Admin, SaaS Scaling, Payment Systems": "🌌",
  "Extensions, Plug-ins, and Software Suite Development": "🔌",
  "Version Control - git, github, gitlab": "<i class='fab fa-github'></i>",
  "Data Science - Big Data": "<i class='fas fa-chart-area'></i>",
  "Data Science - Business": "<i class='fas fa-chart-area'></i>",
  "Data Science - General": "<i class='fas fa-chart-area'></i>",
  "Data Science - Jupyter Notebook": "<i class='fas fa-chart-area'></i>",
  "Data Science - Python": "<i class='fas fa-chart-area'></i>"
}